name: Send Quote

on: workflow_dispatch

jobs:
  publish-sms:
    runs-on: ubuntu-latest
    steps:
      - env:
          API_KEY: ${{ secrets.airtable_token }}
        run: |
          if echo "${{ secrets.airtable_token }}" != ""; then
            curl "https://api.airtable.com/v0/applZLh474nuvYxNE/Phrases?maxRecords=3&view=Grid%20view" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}"
          fi
