name: Send Quote

on: workflow_dispatch

jobs:
  publish-sms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/checkout@v3
      - env:
          API_KEY: ${{ secrets.airtable_token }}
          STUDIO_SID: ${{ secrets.studio_sid }}
          STUDIO_SECRET: ${{ secrets.studio_secret }}
        run: |
          if echo "${{ secrets.airtable_token }}" != ""; then
            quotes=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tblM5pnUaphmuxJhb?fields%5B%5D=phrase" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
          else
            echo "::warning::No Airtable token found!"
          fi
          if echo "${{ secrets.airtable_token }}" != ""; then
            phone_numbers=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tbllxCDF1n7n83XDB?fields%5B%5D=number" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
          else
            echo "::warning::No Airtable token found!"
          fi
          echo $(npm run format --"${quotes}" --"${phone_numbers}")
