name: Send Quote

on: workflow_dispatch

jobs:
  publish-sms:
    runs-on: ubuntu-latest
    steps:
      - env:
          API_KEY: ${{ secrets.airtable_token }}
        run: |
          if echo "${{ secrets.airtable_token }}" != ""; then
            echo "Working!"
          fi
