name: Send Quote

on: 
  workflow_dispatch:
  schedule:
   - cron: '0 11 * * 1'

jobs:
  publish-sms:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.twilio_sid }}
      TWILIO_AUTH_TOKEN: ${{ secrets.twilio_auth_token }}
      FLOW_SID: ${{ secrets.flow_sid }}
      PROXY_NUMBER: ${{ secrets.proxy_number }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/checkout@v3
      - run: |
          npm i
          if echo "${{ secrets.airtable_token }}" != ""; then
            quotes=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/Phrases?maxRecords=3&view=Grid%20view" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
            phone_numbers=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tbltAFtO1BCNYLVEo?fields%5B%5D=number" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
            if current_quote_index_response=$(curl https://api.airtable.com/v0/applZLh474nuvYxNE/Current%20Quote%20Index/rec2Gg9nrCldTPt0N \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}"); then
              echo "current_quote_index_response=${current_quote_index_response}" >> $GITHUB_ENV
            else
              echo "::warning::Failed to get current_quote_index_response from Airtable!"
            echo "phoneNumbers=${phone_numbers}" >> $GITHUB_ENV
            fi
          else
            echo "::warning::No Airtable token found!"
            exit 1
          fi
          if payload=$(node ./format_airtable_data.js "${quotes}" "${phone_numbers}" "${current_quote_index_response}"); then
            echo "payload=${payload}" >> $GITHUB_ENV
          else
            echo "::warning::Failed to map data to JSON!"
            exit 1
          fi
          if echo "${{ secrets.twilio_sid }}" != ""; then
            echo "Twilio Sid found!!"
          else
            echo "::warning::No Twilio SID found!"
          fi
          if echo "${{ secrets.twilio_auth_token}}" != ""; then
            echo "Twilio Auth Token found!"
          else
            echo "::warning::No Twilio Auth Token found!"
          fi
          if echo "${{ secrets.twilio_number }}" == "" || echo "${{ secrets.proxy_number }}" == ""; then
            echo "::warning::Twilio or Proxy number missing!"
          fi
      - uses: MarvJohnson/intern-group-project/actions/conversations@main
      - run: |
          echo "next_quote_index=$(node -p -e "${{ fromJSON(env.current_quote_index_response).fields.index }} + 1")" >> $GITHUB_ENV
      - run: |
          curl -X PATCH https://api.airtable.com/v0/applZLh474nuvYxNE/Current%20Quote%20Index/rec2Gg9nrCldTPt0N \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}" \
            -H "Content-Type: application/json" \
            --data '{
            "fields": {
              "index": ${{ env.next_quote_index }}
            }
          }'
          
          
