name: Send Quote

on: workflow_dispatch

jobs:
  publish-sms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/checkout@v3
      - env:
          API_KEY: ${{ secrets.airtable_token }}
          TWILIO_SID: ${{ secrets.twilio_sid }}
          TWILIO_AUTH_TOKEN: ${{ secrets.twilio_auth_token }}
        run: |
          if echo "${{ secrets.airtable_token }}" != ""; then
            quotes=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/Phrases?maxRecords=3&view=Grid%20view" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
          else
            echo "::warning::No Airtable token found!"
            exit 1
          fi
          if echo "${{ secrets.airtable_token }}" != ""; then
            phone_numbers=$(curl "https://api.airtable.com/v0/applZLh474nuvYxNE/tbllxCDF1n7n83XDB?fields%5B%5D=number" \
            -H "Authorization: Bearer ${{ secrets.airtable_token }}")
          else
            echo "::warning::No Airtable token found!"
            exit 1
          fi
          if ! payload=$(npm run format "${quotes}" "${phone_numbers}"); then
            echo "::warning::Failed to map data to JSON!"
            exit 1
          fi
          curl -X POST "https://studio.twilio.com/v2/Flows/FW738979ea1b5270b6bb2aa62ce1413323/Executions" \
          --data-urlencode "To=${{ secrets.proxy_number }} \
          --data-urlencode "From=${{ secrets.twilio_number }} \
          -u "${{ secrets.twilio_sid }}:${{ secrets.twilio_auth_token }}" \
          -d "${payload}"
